version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    post_install:
      - uv sync --active --frozen

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
