[project]
name = "sphinx-thumb-image"
version = "0.0.1"
description = "Sphinx extension that resizes images into thumbnails on the fly"
authors = [
    {name = "Robpol86",email = "robpol86@gmail.com"}
]
license = {text = "BSD-2-Clause"}
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "sphinx (>=8.2.3,<9.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
